workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: CarloSApp

    environment:
      java: 17
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.carloserlamo.app"
        XCODE_PROJECT: "iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
        APP_ID: 6754875098
        GRADLE_OPTS: "-Xmx6144m -Dorg.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8"

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name:  Force regenerate provisioning profiles
        script: |
          echo ">>> Removing old provisioning profiles"
          app-store-connect delete-provisioning-profiles $BUNDLE_ID || true

          echo ">>> Creating new provisioning profiles"
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create

      - name: Add certificates
        script: |
          keychain add-certificates

      - name: Set up code signing settings
        script: |
          cd $CM_BUILD_DIR/iosApp
          echo ">>> Applying provisioning profiles to Xcode"
          xcode-project use-profiles

      - name: Build KMM framework
        script: |
          echo ">>> Building Kotlin Multiplatform framework"
          cd $CM_BUILD_DIR
          export GRADLE_OPTS="-Xmx6144m -Dkotlin.daemon.jvm.options=-Xmx6144m"
          ./gradlew :composeApp:packForXcode \
            --no-daemon --stacktrace \
            -Pkotlin.native.cacheKind=none \
            -Pkotlin.native.binary.memoryModel=experimental \
            -Porg.gradle.jvmargs="-Xmx6144m"

      - name: Build iOS app
        script: |
          echo ">>> Building iOS IPA"
          cd $CM_BUILD_DIR/iosApp
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - iosApp/build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true